#!/usr/bin/env python3
"""
CFMM Audit Script — Sabre GDS Command Block Validator

Validates Sabre GDS booking commands generated by the Sabre Booking Tool.
Checks Stage 1 (availability/direct sell) and Stage 2 (full PNR block) for
syntax correctness, missing fields, and common formatting issues.

Usage:
    python cfmm_audit.py                    # interactive mode (paste commands)
    python cfmm_audit.py commands.txt       # audit from file
    python cfmm_audit.py -s1 "1AA142Y16MARJFKLHR" -s2 "0AA142Y16MARJFKLHRSS1..."
"""

import re
import sys
from datetime import datetime

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VALID_MONTHS = [
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
    "JUL", "AUG", "SEP", "OCT", "NOV", "DEC",
]

VALID_BOOKING_CLASSES = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

VALID_TITLES = {"MR", "MRS", "MS", "MSTR", "MISS", "DR", "PROF", "REV", "SIR"}

# Stage 1 direct sell:  1AA142Y16MARJFKLHR
STAGE1_DIRECT_RE = re.compile(
    r"^1"
    r"([A-Z0-9]{2})"       # carrier (2 chars)
    r"(\d{1,5})"           # flight number
    r"([A-Z])"             # booking class
    r"(\d{1,2}[A-Z]{3})"  # date (DDMON)
    r"([A-Z]{3})"          # origin
    r"([A-Z]{3})$"         # destination
)

# Stage 1 availability: 116MARJFKLHR  or  116MARJFKLHR/AA
STAGE1_AVAIL_RE = re.compile(
    r"^1"
    r"(\d{1,2}[A-Z]{3})"  # date
    r"([A-Z]{3})"          # origin
    r"([A-Z]{3})"          # destination
    r"(?:/([A-Z0-9]{2}))?$"  # optional carrier
)

# Stage 2 sell: 0AA142Y16MARJFKLHRSS1
STAGE2_SELL_RE = re.compile(
    r"^0"
    r"([A-Z0-9]{2})"       # carrier
    r"(\d{1,5})"           # flight number
    r"([A-Z])"             # booking class
    r"(\d{1,2}[A-Z]{3})"  # date
    r"([A-Z]{3})"          # origin
    r"([A-Z]{3})"          # destination
    r"SS(\d+)$"            # segment status + count
)

# Passenger name: -SMITH/JOHNMR
STAGE2_PAX_RE = re.compile(
    r"^-([A-Z]+)/([A-Z]+)(MR|MRS|MS|MSTR|MISS|DR|PROF|REV|SIR)$"
)

# Phone: 92125551234-A  or  92125551234-B
STAGE2_PHONE_RE = re.compile(r"^9(\d+)-(A|B)$")

# Email: APE-user//domain..com
STAGE2_EMAIL_RE = re.compile(r"^APE-(.+)$")

# Frequent flyer: FFDLAA1234567890-1.1
STAGE2_FF_RE = re.compile(r"^FFDL([A-Z]{2})(\S+)-(\d+\.\d+)$")

# SSR: 3VGML-1.1
STAGE2_SSR_RE = re.compile(r"^3(.+)-(\d+\.\d+)$")

# Ticketing deadline: 7TAW16MAR/
STAGE2_TICK_RE = re.compile(r"^7TAW(\d{1,2}[A-Z]{3})/$")

# Received from: 6SMITH
STAGE2_RCVD_RE = re.compile(r"^6([A-Z]+)$")

# End record
STAGE2_END_RE = re.compile(r"^ER$")


# ---------------------------------------------------------------------------
# Audit result tracking
# ---------------------------------------------------------------------------

class AuditResult:
    """Collects pass/fail/warning findings for an audit run."""

    def __init__(self):
        self.findings = []  # list of (severity, line_num, message)
        self.stats = {
            "segments": 0,
            "passengers": 0,
            "has_phone": False,
            "has_email": False,
            "has_ff": False,
            "has_ssr": False,
            "has_ticketing": False,
            "has_received_from": False,
            "has_end_record": False,
        }

    def error(self, line_num, msg):
        self.findings.append(("ERROR", line_num, msg))

    def warn(self, line_num, msg):
        self.findings.append(("WARN", line_num, msg))

    def info(self, line_num, msg):
        self.findings.append(("INFO", line_num, msg))

    @property
    def errors(self):
        return [f for f in self.findings if f[0] == "ERROR"]

    @property
    def warnings(self):
        return [f for f in self.findings if f[0] == "WARN"]

    @property
    def passed(self):
        return len(self.errors) == 0


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def validate_date(date_str):
    """Check DDMON date format (e.g., 16MAR). Returns (valid, message)."""
    m = re.match(r"^(\d{1,2})([A-Z]{3})$", date_str)
    if not m:
        return False, f"Invalid date format: '{date_str}' (expected DDMON, e.g. 16MAR)"
    day, month = int(m.group(1)), m.group(2)
    if month not in VALID_MONTHS:
        return False, f"Invalid month: '{month}'"
    if day < 1 or day > 31:
        return False, f"Invalid day: {day}"
    return True, ""


def validate_iata_airport(code):
    """Basic IATA airport code validation (3 uppercase letters)."""
    if not re.match(r"^[A-Z]{3}$", code):
        return False, f"Invalid IATA airport code: '{code}' (expected 3 letters)"
    return True, ""


def validate_iata_airline(code):
    """Basic IATA airline code validation (2 alphanumeric chars)."""
    if not re.match(r"^[A-Z0-9]{2}$", code):
        return False, f"Invalid IATA airline code: '{code}' (expected 2 alphanumeric)"
    return True, ""


def validate_booking_class(cls):
    """Check single-letter booking class."""
    if cls not in VALID_BOOKING_CLASSES:
        return False, f"Invalid booking class: '{cls}'"
    return True, ""


# ---------------------------------------------------------------------------
# Stage 1 auditor
# ---------------------------------------------------------------------------

def audit_stage1(lines, result):
    """Audit Stage 1 command block lines."""
    if not lines:
        result.warn(0, "Stage 1 block is empty")
        return

    for i, line in enumerate(lines, start=1):
        line = line.strip()
        if not line or line.startswith("//"):
            if line.startswith("//"):
                result.warn(i, f"Placeholder/incomplete line: {line}")
            continue

        # Try direct sell format
        m = STAGE1_DIRECT_RE.match(line)
        if m:
            carrier, flightnum, bclass, date, origin, dest = m.groups()
            result.stats["segments"] += 1
            result.info(i, f"Direct sell: {carrier}{flightnum} class {bclass} {date} {origin}-{dest}")

            ok, msg = validate_iata_airline(carrier)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_booking_class(bclass)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_date(date)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(origin)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(dest)
            if not ok:
                result.error(i, msg)
            if origin == dest:
                result.error(i, f"Origin and destination are the same: {origin}")
            continue

        # Try availability format
        m = STAGE1_AVAIL_RE.match(line)
        if m:
            date, origin, dest, carrier = m.groups()
            result.stats["segments"] += 1
            carrier_str = f"/{carrier}" if carrier else ""
            result.info(i, f"Availability check: {date} {origin}-{dest}{carrier_str}")

            ok, msg = validate_date(date)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(origin)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(dest)
            if not ok:
                result.error(i, msg)
            if carrier:
                ok, msg = validate_iata_airline(carrier)
                if not ok:
                    result.error(i, msg)
            if origin == dest:
                result.error(i, f"Origin and destination are the same: {origin}")
            continue

        result.error(i, f"Unrecognized Stage 1 command: {line}")


# ---------------------------------------------------------------------------
# Stage 2 auditor
# ---------------------------------------------------------------------------

def audit_stage2(lines, result):
    """Audit Stage 2 (full PNR block) lines."""
    if not lines:
        result.warn(0, "Stage 2 block is empty")
        return

    segments = []
    passengers = []

    for i, line in enumerate(lines, start=1):
        line = line.strip()
        if not line:
            continue
        if line.startswith("//"):
            result.warn(i, f"Placeholder/incomplete line: {line}")
            continue

        # Sell line
        m = STAGE2_SELL_RE.match(line)
        if m:
            carrier, flightnum, bclass, date, origin, dest, count = m.groups()
            segments.append({
                "carrier": carrier, "flight": flightnum, "class": bclass,
                "date": date, "origin": origin, "dest": dest, "count": int(count),
            })
            result.info(i, f"Sell: {carrier}{flightnum} {bclass} {date} {origin}-{dest} SS{count}")

            ok, msg = validate_iata_airline(carrier)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_booking_class(bclass)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_date(date)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(origin)
            if not ok:
                result.error(i, msg)
            ok, msg = validate_iata_airport(dest)
            if not ok:
                result.error(i, msg)
            if origin == dest:
                result.error(i, f"Origin and destination are the same: {origin}")
            continue

        # Passenger name
        m = STAGE2_PAX_RE.match(line)
        if m:
            last, first, title = m.groups()
            passengers.append({"last": last, "first": first, "title": title})
            result.stats["passengers"] += 1
            result.info(i, f"Passenger: {last}/{first} {title}")
            if title not in VALID_TITLES:
                result.warn(i, f"Unusual title: '{title}'")
            continue

        # Phone
        m = STAGE2_PHONE_RE.match(line)
        if m:
            phone, phone_type = m.groups()
            label = "Agency phone" if phone_type == "A" else "Passenger phone"
            result.stats["has_phone"] = True
            result.info(i, f"{label}: {phone}")
            if len(phone) < 7:
                result.warn(i, f"Phone number seems too short: {phone}")
            if len(phone) > 15:
                result.warn(i, f"Phone number seems too long: {phone}")
            continue

        # Email
        m = STAGE2_EMAIL_RE.match(line)
        if m:
            raw_email = m.group(1)
            # Reverse Sabre encoding: // -> @, .. -> _
            decoded = raw_email.replace("//", "@").replace("..", "_")
            result.stats["has_email"] = True
            result.info(i, f"Email: {decoded}")
            if "@" not in decoded:
                result.warn(i, f"Decoded email missing '@': {decoded}")
            continue

        # Frequent flyer
        m = STAGE2_FF_RE.match(line)
        if m:
            ff_airline, ff_num, pax_ref = m.groups()
            result.stats["has_ff"] = True
            result.info(i, f"Frequent flyer: {ff_airline}-{ff_num} (pax {pax_ref})")
            continue

        # SSR
        m = STAGE2_SSR_RE.match(line)
        if m:
            ssr_code, pax_ref = m.groups()
            result.stats["has_ssr"] = True
            result.info(i, f"SSR: {ssr_code} (pax {pax_ref})")
            continue

        # Ticketing deadline
        m = STAGE2_TICK_RE.match(line)
        if m:
            tick_date = m.group(1)
            result.stats["has_ticketing"] = True
            result.info(i, f"Ticketing deadline: {tick_date}")
            ok, msg = validate_date(tick_date)
            if not ok:
                result.error(i, msg)
            continue

        # Received from
        m = STAGE2_RCVD_RE.match(line)
        if m:
            name = m.group(1)
            result.stats["has_received_from"] = True
            result.info(i, f"Received from: {name}")
            continue

        # End record
        if STAGE2_END_RE.match(line):
            result.stats["has_end_record"] = True
            result.info(i, "End record (ER)")
            continue

        result.warn(i, f"Unrecognized Stage 2 line: {line}")

    # Cross-field validation
    if not segments:
        result.error(0, "No sell segments found in Stage 2")
    if not passengers:
        result.error(0, "No passenger names found in Stage 2")
    if not result.stats["has_phone"]:
        result.error(0, "Missing phone number (required for PNR)")
    if not result.stats["has_ticketing"]:
        result.error(0, "Missing ticketing deadline (7TAW line)")
    if not result.stats["has_received_from"]:
        result.error(0, "Missing received-from field")
    if not result.stats["has_end_record"]:
        result.error(0, "Missing end record (ER) — PNR will not be saved")

    # Check segment continuity (destination of seg N should match origin of seg N+1)
    for j in range(len(segments) - 1):
        if segments[j]["dest"] != segments[j + 1]["origin"]:
            result.warn(
                0,
                f"Route gap: segment {j+1} ends at {segments[j]['dest']} "
                f"but segment {j+2} starts at {segments[j+1]['origin']}",
            )

    # Check SS count vs passenger count
    for j, seg in enumerate(segments):
        if passengers and seg["count"] != len(passengers):
            result.warn(
                0,
                f"Segment {j+1} sells {seg['count']} seat(s) "
                f"but {len(passengers)} passenger(s) listed",
            )

    if not result.stats["has_email"]:
        result.warn(0, "No email address — recommended for e-ticket delivery")


# ---------------------------------------------------------------------------
# Report formatter
# ---------------------------------------------------------------------------

def format_report(result, stage1_lines, stage2_lines):
    """Format a human-readable audit report."""
    border = "=" * 60
    divider = "-" * 60
    lines = []

    lines.append(border)
    lines.append("  CFMM AUDIT REPORT — Sabre GDS Command Validator")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(border)
    lines.append("")

    # Summary
    seg_count = result.stats["segments"]
    pax_count = result.stats["passengers"]
    err_count = len(result.errors)
    warn_count = len(result.warnings)

    status = "PASS" if result.passed else "FAIL"
    lines.append(f"  Status:     [{status}]")
    lines.append(f"  Segments:   {seg_count}")
    lines.append(f"  Passengers: {pax_count}")
    lines.append(f"  Errors:     {err_count}")
    lines.append(f"  Warnings:   {warn_count}")
    lines.append("")

    # Field checklist
    lines.append(divider)
    lines.append("  FIELD CHECKLIST")
    lines.append(divider)
    checks = [
        ("Phone", result.stats["has_phone"]),
        ("Email", result.stats["has_email"]),
        ("Frequent Flyer", result.stats["has_ff"]),
        ("SSR", result.stats["has_ssr"]),
        ("Ticketing Deadline", result.stats["has_ticketing"]),
        ("Received From", result.stats["has_received_from"]),
        ("End Record (ER)", result.stats["has_end_record"]),
    ]
    for label, present in checks:
        marker = "[x]" if present else "[ ]"
        lines.append(f"  {marker} {label}")
    lines.append("")

    # Errors
    if result.errors:
        lines.append(divider)
        lines.append("  ERRORS")
        lines.append(divider)
        for sev, line_num, msg in result.errors:
            loc = f"line {line_num}" if line_num else "general"
            lines.append(f"  !! {loc}: {msg}")
        lines.append("")

    # Warnings
    if result.warnings:
        lines.append(divider)
        lines.append("  WARNINGS")
        lines.append(divider)
        for sev, line_num, msg in result.warnings:
            loc = f"line {line_num}" if line_num else "general"
            lines.append(f"   ? {loc}: {msg}")
        lines.append("")

    # Raw commands echoed
    lines.append(divider)
    lines.append("  STAGE 1 COMMANDS")
    lines.append(divider)
    if stage1_lines:
        for l in stage1_lines:
            lines.append(f"  {l}")
    else:
        lines.append("  (none)")
    lines.append("")

    lines.append(divider)
    lines.append("  STAGE 2 COMMANDS")
    lines.append(divider)
    if stage2_lines:
        for l in stage2_lines:
            lines.append(f"  {l}")
    else:
        lines.append("  (none)")
    lines.append("")
    lines.append(border)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Input parsing — split into Stage 1 / Stage 2 blocks
# ---------------------------------------------------------------------------

def parse_input(text):
    """
    Parse raw input text into Stage 1 and Stage 2 line lists.
    Supports several input formats:
      - Two blocks separated by a blank line
      - Lines starting with '1' (Stage 1) and '0'/'-'/etc (Stage 2)
      - Explicit markers like "STAGE 1" / "STAGE 2" or "---"
    """
    raw_lines = [l.rstrip() for l in text.strip().splitlines()]

    # Check for explicit stage markers
    stage1, stage2 = [], []
    current_stage = None

    for line in raw_lines:
        upper = line.strip().upper()
        if "STAGE 1" in upper or "STAGE1" in upper:
            current_stage = 1
            continue
        if "STAGE 2" in upper or "STAGE2" in upper:
            current_stage = 2
            continue
        if upper == "---":
            if current_stage == 1:
                current_stage = 2
            continue

        stripped = line.strip()
        if not stripped:
            # Blank line might separate stages
            if current_stage == 1 and stage1 and not stage2:
                current_stage = 2
            continue

        if current_stage == 1:
            stage1.append(stripped)
        elif current_stage == 2:
            stage2.append(stripped)
        else:
            # Auto-detect: lines starting with '1' are Stage 1,
            # everything else goes to Stage 2
            if stripped.startswith("1") and not stage2:
                stage1.append(stripped)
            else:
                stage2.append(stripped)

    return stage1, stage2


# ---------------------------------------------------------------------------
# CLI entry
# ---------------------------------------------------------------------------

def run_audit(text):
    """Run full audit on command text, return (report_string, passed)."""
    stage1_lines, stage2_lines = parse_input(text)
    result = AuditResult()

    # Reset segment count for stage 2 (stage 1 count is informational)
    s1_result = AuditResult()
    audit_stage1(stage1_lines, s1_result)

    audit_stage2(stage2_lines, result)

    # Merge stage 1 findings (prefix with "S1 ")
    for sev, ln, msg in s1_result.findings:
        if sev == "ERROR":
            result.error(ln, f"[Stage 1] {msg}")
        elif sev == "WARN":
            result.warn(ln, f"[Stage 1] {msg}")
        else:
            result.info(ln, f"[Stage 1] {msg}")

    # Transfer segment count from stage 1 if stage 2 had none
    if s1_result.stats["segments"] > 0:
        result.stats["segments"] = max(
            result.stats["segments"], s1_result.stats["segments"]
        )

    report = format_report(result, stage1_lines, stage2_lines)
    return report, result.passed


def demo_audit():
    """Run audit on a built-in example to demonstrate functionality."""
    example = """STAGE 1
1AA142Y16MARJFKLHR
1BA456J17MARLHRCDG

STAGE 2
0AA142Y16MARJFKLHRSS1
0BA456J17MARLHRCDGSS1
-SMITH/JOHNMR
92125551234-A
APE-john.smith//gmail..com
FFDLAA1234567890-1.1
3VGML-1.1
7TAW10MAR/
6SMITH
ER"""
    report, passed = run_audit(example)
    print(report)
    return passed


def main():
    args = sys.argv[1:]

    # Demo / help flags
    if "--help" in args or "-h" in args:
        print(__doc__)
        sys.exit(0)

    if "--demo" in args:
        passed = demo_audit()
        sys.exit(0 if passed else 1)

    # Inline stage arguments: -s1 "..." -s2 "..."
    if "-s1" in args or "-s2" in args:
        s1 = ""
        s2 = ""
        if "-s1" in args:
            idx = args.index("-s1")
            if idx + 1 < len(args):
                s1 = args[idx + 1].replace("\\n", "\n")
        if "-s2" in args:
            idx = args.index("-s2")
            if idx + 1 < len(args):
                s2 = args[idx + 1].replace("\\n", "\n")
        text = f"STAGE 1\n{s1}\n\nSTAGE 2\n{s2}"
        report, passed = run_audit(text)
        print(report)
        sys.exit(0 if passed else 1)

    # File argument
    if args and not args[0].startswith("-"):
        filepath = args[0]
        try:
            with open(filepath, "r") as f:
                text = f.read()
        except FileNotFoundError:
            print(f"Error: file not found: {filepath}", file=sys.stderr)
            sys.exit(2)
        report, passed = run_audit(text)
        print(report)
        sys.exit(0 if passed else 1)

    # Interactive mode — read from stdin
    print("CFMM Audit — Paste Sabre commands below (Ctrl+D to finish):")
    print("  Separate Stage 1 and Stage 2 with a blank line or 'STAGE 1'/'STAGE 2' headers.")
    print()
    try:
        text = sys.stdin.read()
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(130)

    if not text.strip():
        print("No input provided. Use --demo for an example or --help for usage.")
        sys.exit(0)

    report, passed = run_audit(text)
    print(report)
    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
